name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK for Backend
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: temurin

      - name: Set execute permissions for mvnw
        run: | 
          cd Phonebook
          chmod +x mvnw

      - name: Set up backend dependencies and build
        run: |
          cd Phonebook
          ./mvnw clean compile package -DskipTests

      - name: Run tests if any
        run: |
          cd Phonebook
          ./mvnw test
